sudo: required
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install ansible
  #- pip install pylint
  - pip install flake8
  - pip install pycodestyle
  - ansible --version

# command to run tests
script:
  # With pylint ignore
  #   logging-format-interpolation: Use % formatting in logging functions
  #   global-statement : Using the global statement
  #- pylint *.py -d logging-format-interpolation -d global-statement 

  # With flake ignore
  #  F403: <module> import *' used; unable to detect undefined names
  #  F405: <var> may be undefined, or defined from star imports
  #  W503: line break before binary operator (PEP8 advices to put logical operator ahead)
  - flake8 *.py --max-line-length=100 --ignore F403,F405,W503

  # pycodestyle (PEP8)
  - pycodestyle *.py --max-line-length=100

